name: "Increment Environment variable"
author: "evanallen13"
description: "Action to increment an Environment variable by 1."

inputs:
  name:
    description: Name
    required: true

  runs:
    using: node20
    main: dist/index.js