name: "Increment Environment Variable"
author: "evanallen13"
description: "Action to increment an Environment variable by 1."

branding:
  icon: 'play-circle'
  color: 'purple'

inputs:
  name:
    description: "Name"
    required: true

runs:
  using: node20
  main: dist/index.js